[package]
name = "rusty_analytics"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple analytics library for Rust and the Rusty Road web framework"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
